/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gyro.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gyro.pb-c.h"
void   spotv2__gyro__accel__init
                     (Spotv2__Gyro__Accel         *message)
{
  static const Spotv2__Gyro__Accel init_value = SPOTV2__GYRO__ACCEL__INIT;
  *message = init_value;
}
void   spotv2__gyro__gyro__init
                     (Spotv2__Gyro__Gyro         *message)
{
  static const Spotv2__Gyro__Gyro init_value = SPOTV2__GYRO__GYRO__INIT;
  *message = init_value;
}
void   spotv2__gyro__mag__init
                     (Spotv2__Gyro__Mag         *message)
{
  static const Spotv2__Gyro__Mag init_value = SPOTV2__GYRO__MAG__INIT;
  *message = init_value;
}
void   spotv2__gyro__grav__init
                     (Spotv2__Gyro__Grav         *message)
{
  static const Spotv2__Gyro__Grav init_value = SPOTV2__GYRO__GRAV__INIT;
  *message = init_value;
}
void   spotv2__gyro__linear_accel__init
                     (Spotv2__Gyro__LinearAccel         *message)
{
  static const Spotv2__Gyro__LinearAccel init_value = SPOTV2__GYRO__LINEAR_ACCEL__INIT;
  *message = init_value;
}
void   spotv2__gyro__quat6__init
                     (Spotv2__Gyro__Quat6         *message)
{
  static const Spotv2__Gyro__Quat6 init_value = SPOTV2__GYRO__QUAT6__INIT;
  *message = init_value;
}
void   spotv2__gyro__quat9__init
                     (Spotv2__Gyro__Quat9         *message)
{
  static const Spotv2__Gyro__Quat9 init_value = SPOTV2__GYRO__QUAT9__INIT;
  *message = init_value;
}
void   spotv2__gyro__euler6__init
                     (Spotv2__Gyro__Euler6         *message)
{
  static const Spotv2__Gyro__Euler6 init_value = SPOTV2__GYRO__EULER6__INIT;
  *message = init_value;
}
void   spotv2__gyro__euler9__init
                     (Spotv2__Gyro__Euler9         *message)
{
  static const Spotv2__Gyro__Euler9 init_value = SPOTV2__GYRO__EULER9__INIT;
  *message = init_value;
}
void   spotv2__gyro__init
                     (Spotv2__Gyro         *message)
{
  static const Spotv2__Gyro init_value = SPOTV2__GYRO__INIT;
  *message = init_value;
}
size_t spotv2__gyro__get_packed_size
                     (const Spotv2__Gyro *message)
{
  assert(message->base.descriptor == &spotv2__gyro__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__gyro__pack
                     (const Spotv2__Gyro *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__gyro__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__gyro__pack_to_buffer
                     (const Spotv2__Gyro *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__gyro__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Gyro *
       spotv2__gyro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Gyro *)
     protobuf_c_message_unpack (&spotv2__gyro__descriptor,
                                allocator, len, data);
}
void   spotv2__gyro__free_unpacked
                     (Spotv2__Gyro *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__gyro__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor spotv2__gyro__accel__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Accel, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Accel, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Accel, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__accel__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange spotv2__gyro__accel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__gyro__accel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.Accel",
  "Accel",
  "Spotv2__Gyro__Accel",
  "spotv2",
  sizeof(Spotv2__Gyro__Accel),
  3,
  spotv2__gyro__accel__field_descriptors,
  spotv2__gyro__accel__field_indices_by_name,
  1,  spotv2__gyro__accel__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__accel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__gyro__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Gyro, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Gyro, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Gyro, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__gyro__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange spotv2__gyro__gyro__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__gyro__gyro__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.Gyro",
  "Gyro",
  "Spotv2__Gyro__Gyro",
  "spotv2",
  sizeof(Spotv2__Gyro__Gyro),
  3,
  spotv2__gyro__gyro__field_descriptors,
  spotv2__gyro__gyro__field_indices_by_name,
  1,  spotv2__gyro__gyro__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__gyro__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__mag__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Mag, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Mag, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Mag, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__mag__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange spotv2__gyro__mag__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__gyro__mag__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.Mag",
  "Mag",
  "Spotv2__Gyro__Mag",
  "spotv2",
  sizeof(Spotv2__Gyro__Mag),
  3,
  spotv2__gyro__mag__field_descriptors,
  spotv2__gyro__mag__field_indices_by_name,
  1,  spotv2__gyro__mag__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__mag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__grav__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Grav, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Grav, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Grav, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__grav__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange spotv2__gyro__grav__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__gyro__grav__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.Grav",
  "Grav",
  "Spotv2__Gyro__Grav",
  "spotv2",
  sizeof(Spotv2__Gyro__Grav),
  3,
  spotv2__gyro__grav__field_descriptors,
  spotv2__gyro__grav__field_indices_by_name,
  1,  spotv2__gyro__grav__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__grav__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__linear_accel__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__LinearAccel, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__LinearAccel, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__LinearAccel, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__linear_accel__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange spotv2__gyro__linear_accel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__gyro__linear_accel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.LinearAccel",
  "LinearAccel",
  "Spotv2__Gyro__LinearAccel",
  "spotv2",
  sizeof(Spotv2__Gyro__LinearAccel),
  3,
  spotv2__gyro__linear_accel__field_descriptors,
  spotv2__gyro__linear_accel__field_indices_by_name,
  1,  spotv2__gyro__linear_accel__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__linear_accel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__quat6__field_descriptors[4] =
{
  {
    "w",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Quat6, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Quat6, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Quat6, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Quat6, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__quat6__field_indices_by_name[] = {
  0,   /* field[0] = w */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
  3,   /* field[3] = z */
};
static const ProtobufCIntRange spotv2__gyro__quat6__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor spotv2__gyro__quat6__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.Quat6",
  "Quat6",
  "Spotv2__Gyro__Quat6",
  "spotv2",
  sizeof(Spotv2__Gyro__Quat6),
  4,
  spotv2__gyro__quat6__field_descriptors,
  spotv2__gyro__quat6__field_indices_by_name,
  1,  spotv2__gyro__quat6__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__quat6__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__quat9__field_descriptors[4] =
{
  {
    "w",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Quat9, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Quat9, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Quat9, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Quat9, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__quat9__field_indices_by_name[] = {
  0,   /* field[0] = w */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
  3,   /* field[3] = z */
};
static const ProtobufCIntRange spotv2__gyro__quat9__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor spotv2__gyro__quat9__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.Quat9",
  "Quat9",
  "Spotv2__Gyro__Quat9",
  "spotv2",
  sizeof(Spotv2__Gyro__Quat9),
  4,
  spotv2__gyro__quat9__field_descriptors,
  spotv2__gyro__quat9__field_indices_by_name,
  1,  spotv2__gyro__quat9__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__quat9__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__euler6__field_descriptors[3] =
{
  {
    "roll",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Euler6, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Euler6, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Euler6, yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__euler6__field_indices_by_name[] = {
  1,   /* field[1] = pitch */
  0,   /* field[0] = roll */
  2,   /* field[2] = yaw */
};
static const ProtobufCIntRange spotv2__gyro__euler6__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__gyro__euler6__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.Euler6",
  "Euler6",
  "Spotv2__Gyro__Euler6",
  "spotv2",
  sizeof(Spotv2__Gyro__Euler6),
  3,
  spotv2__gyro__euler6__field_descriptors,
  spotv2__gyro__euler6__field_indices_by_name,
  1,  spotv2__gyro__euler6__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__euler6__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__euler9__field_descriptors[3] =
{
  {
    "roll",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Euler9, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Euler9, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro__Euler9, yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__euler9__field_indices_by_name[] = {
  1,   /* field[1] = pitch */
  0,   /* field[0] = roll */
  2,   /* field[2] = yaw */
};
static const ProtobufCIntRange spotv2__gyro__euler9__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__gyro__euler9__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro.Euler9",
  "Euler9",
  "Spotv2__Gyro__Euler9",
  "spotv2",
  sizeof(Spotv2__Gyro__Euler9),
  3,
  spotv2__gyro__euler9__field_descriptors,
  spotv2__gyro__euler9__field_indices_by_name,
  1,  spotv2__gyro__euler9__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__euler9__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__gyro__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steps",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, steps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__field_indices_by_name[] = {
  1,   /* field[1] = steps */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange spotv2__gyro__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor spotv2__gyro__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro",
  "Gyro",
  "Spotv2__Gyro",
  "spotv2",
  sizeof(Spotv2__Gyro),
  2,
  spotv2__gyro__field_descriptors,
  spotv2__gyro__field_indices_by_name,
  2,  spotv2__gyro__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__init,
  NULL,NULL,NULL    /* reserved[123] */
};
