/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gyro.proto */

#ifndef PROTOBUF_C_gyro_2eproto__INCLUDED
#define PROTOBUF_C_gyro_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"

typedef struct Spotv2__Gyro Spotv2__Gyro;
typedef struct Spotv2__Gyro__Accel Spotv2__Gyro__Accel;
typedef struct Spotv2__Gyro__Gyro Spotv2__Gyro__Gyro;
typedef struct Spotv2__Gyro__Mag Spotv2__Gyro__Mag;
typedef struct Spotv2__Gyro__Grav Spotv2__Gyro__Grav;
typedef struct Spotv2__Gyro__LinearAccel Spotv2__Gyro__LinearAccel;
typedef struct Spotv2__Gyro__Quat6 Spotv2__Gyro__Quat6;
typedef struct Spotv2__Gyro__Quat9 Spotv2__Gyro__Quat9;
typedef struct Spotv2__Gyro__Euler6 Spotv2__Gyro__Euler6;
typedef struct Spotv2__Gyro__Euler9 Spotv2__Gyro__Euler9;


/* --- enums --- */


/* --- messages --- */

struct  Spotv2__Gyro__Accel
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define SPOTV2__GYRO__ACCEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__accel__descriptor) \
, 0, 0, 0 }


struct  Spotv2__Gyro__Gyro
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define SPOTV2__GYRO__GYRO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__gyro__descriptor) \
, 0, 0, 0 }


struct  Spotv2__Gyro__Mag
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define SPOTV2__GYRO__MAG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__mag__descriptor) \
, 0, 0, 0 }


struct  Spotv2__Gyro__Grav
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define SPOTV2__GYRO__GRAV__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__grav__descriptor) \
, 0, 0, 0 }


struct  Spotv2__Gyro__LinearAccel
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define SPOTV2__GYRO__LINEAR_ACCEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__linear_accel__descriptor) \
, 0, 0, 0 }


struct  Spotv2__Gyro__Quat6
{
  ProtobufCMessage base;
  float w;
  float x;
  float y;
  float z;
};
#define SPOTV2__GYRO__QUAT6__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__quat6__descriptor) \
, 0, 0, 0, 0 }


struct  Spotv2__Gyro__Quat9
{
  ProtobufCMessage base;
  float w;
  float x;
  float y;
  float z;
};
#define SPOTV2__GYRO__QUAT9__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__quat9__descriptor) \
, 0, 0, 0, 0 }


struct  Spotv2__Gyro__Euler6
{
  ProtobufCMessage base;
  float roll;
  float pitch;
  float yaw;
};
#define SPOTV2__GYRO__EULER6__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__euler6__descriptor) \
, 0, 0, 0 }


struct  Spotv2__Gyro__Euler9
{
  ProtobufCMessage base;
  float roll;
  float pitch;
  float yaw;
};
#define SPOTV2__GYRO__EULER9__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__euler9__descriptor) \
, 0, 0, 0 }


struct  Spotv2__Gyro
{
  ProtobufCMessage base;
  Google__Protobuf__Timestamp *timestamp;
  uint64_t steps;
};
#define SPOTV2__GYRO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__descriptor) \
, NULL, 0 }


/* Spotv2__Gyro__Accel methods */
void   spotv2__gyro__accel__init
                     (Spotv2__Gyro__Accel         *message);
/* Spotv2__Gyro__Gyro methods */
void   spotv2__gyro__gyro__init
                     (Spotv2__Gyro__Gyro         *message);
/* Spotv2__Gyro__Mag methods */
void   spotv2__gyro__mag__init
                     (Spotv2__Gyro__Mag         *message);
/* Spotv2__Gyro__Grav methods */
void   spotv2__gyro__grav__init
                     (Spotv2__Gyro__Grav         *message);
/* Spotv2__Gyro__LinearAccel methods */
void   spotv2__gyro__linear_accel__init
                     (Spotv2__Gyro__LinearAccel         *message);
/* Spotv2__Gyro__Quat6 methods */
void   spotv2__gyro__quat6__init
                     (Spotv2__Gyro__Quat6         *message);
/* Spotv2__Gyro__Quat9 methods */
void   spotv2__gyro__quat9__init
                     (Spotv2__Gyro__Quat9         *message);
/* Spotv2__Gyro__Euler6 methods */
void   spotv2__gyro__euler6__init
                     (Spotv2__Gyro__Euler6         *message);
/* Spotv2__Gyro__Euler9 methods */
void   spotv2__gyro__euler9__init
                     (Spotv2__Gyro__Euler9         *message);
/* Spotv2__Gyro methods */
void   spotv2__gyro__init
                     (Spotv2__Gyro         *message);
size_t spotv2__gyro__get_packed_size
                     (const Spotv2__Gyro   *message);
size_t spotv2__gyro__pack
                     (const Spotv2__Gyro   *message,
                      uint8_t             *out);
size_t spotv2__gyro__pack_to_buffer
                     (const Spotv2__Gyro   *message,
                      ProtobufCBuffer     *buffer);
Spotv2__Gyro *
       spotv2__gyro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   spotv2__gyro__free_unpacked
                     (Spotv2__Gyro *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Spotv2__Gyro__Accel_Closure)
                 (const Spotv2__Gyro__Accel *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro__Gyro_Closure)
                 (const Spotv2__Gyro__Gyro *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro__Mag_Closure)
                 (const Spotv2__Gyro__Mag *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro__Grav_Closure)
                 (const Spotv2__Gyro__Grav *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro__LinearAccel_Closure)
                 (const Spotv2__Gyro__LinearAccel *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro__Quat6_Closure)
                 (const Spotv2__Gyro__Quat6 *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro__Quat9_Closure)
                 (const Spotv2__Gyro__Quat9 *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro__Euler6_Closure)
                 (const Spotv2__Gyro__Euler6 *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro__Euler9_Closure)
                 (const Spotv2__Gyro__Euler9 *message,
                  void *closure_data);
typedef void (*Spotv2__Gyro_Closure)
                 (const Spotv2__Gyro *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor spotv2__gyro__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__accel__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__gyro__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__mag__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__grav__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__linear_accel__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__quat6__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__quat9__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__euler6__descriptor;
extern const ProtobufCMessageDescriptor spotv2__gyro__euler9__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_gyro_2eproto__INCLUDED */
