# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gyro.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngyro.proto\x12\x06spotv2\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n\x08Position\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nfrontAngle\x18\x05 \x01(\x01\x12\x11\n\tsideAngle\x18\x06 \x01(\x01\x1a\x80\x01\n\x03Raw\x1a(\n\x05\x41\x63\x63\x65l\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\'\n\x04Gyro\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a&\n\x03Mag\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gyro_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSITION']._serialized_start=56
  _globals['_POSITION']._serialized_end=283
  _globals['_POSITION_RAW']._serialized_start=155
  _globals['_POSITION_RAW']._serialized_end=283
  _globals['_POSITION_RAW_ACCEL']._serialized_start=162
  _globals['_POSITION_RAW_ACCEL']._serialized_end=202
  _globals['_POSITION_RAW_GYRO']._serialized_start=204
  _globals['_POSITION_RAW_GYRO']._serialized_end=243
  _globals['_POSITION_RAW_MAG']._serialized_start=245
  _globals['_POSITION_RAW_MAG']._serialized_end=283
# @@protoc_insertion_point(module_scope)
