/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gyro.proto */

#ifndef PROTOBUF_C_gyro_2eproto__INCLUDED
#define PROTOBUF_C_gyro_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Spotv2__Gyro Spotv2__Gyro;


/* --- enums --- */


/* --- messages --- */

struct  Spotv2__Gyro
{
  ProtobufCMessage base;
  float accel_x;
  float accel_y;
  float accel_z;
  float gyro_x;
  float gyro_y;
  float gyro_z;
  float mag_x;
  float mag_y;
  float mag_z;
  float grav_x;
  float grav_y;
  float grav_z;
  float linearaccel_x;
  float linearaccel_y;
  float linearaccel_z;
  float quat6_w;
  float quat6_x;
  float quat6_y;
  float quat6_z;
  float quat9_w;
  float quat9_x;
  float quat9_y;
  float quat9_z;
  float euler6_roll;
  float euler6_pitch;
  float euler6_yaw;
  float euler9_roll;
  float euler9_pitch;
  float euler9_yaw;
  uint64_t steps;
};
#define SPOTV2__GYRO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__gyro__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Spotv2__Gyro methods */
void   spotv2__gyro__init
                     (Spotv2__Gyro         *message);
size_t spotv2__gyro__get_packed_size
                     (const Spotv2__Gyro   *message);
size_t spotv2__gyro__pack
                     (const Spotv2__Gyro   *message,
                      uint8_t             *out);
size_t spotv2__gyro__pack_to_buffer
                     (const Spotv2__Gyro   *message,
                      ProtobufCBuffer     *buffer);
Spotv2__Gyro *
       spotv2__gyro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   spotv2__gyro__free_unpacked
                     (Spotv2__Gyro *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Spotv2__Gyro_Closure)
                 (const Spotv2__Gyro *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor spotv2__gyro__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_gyro_2eproto__INCLUDED */
