/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gyro.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gyro.pb-c.h"
void   spotv2__gyro__init
                     (Spotv2__Gyro         *message)
{
  static const Spotv2__Gyro init_value = SPOTV2__GYRO__INIT;
  *message = init_value;
}
size_t spotv2__gyro__get_packed_size
                     (const Spotv2__Gyro *message)
{
  assert(message->base.descriptor == &spotv2__gyro__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__gyro__pack
                     (const Spotv2__Gyro *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__gyro__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__gyro__pack_to_buffer
                     (const Spotv2__Gyro *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__gyro__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Gyro *
       spotv2__gyro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Gyro *)
     protobuf_c_message_unpack (&spotv2__gyro__descriptor,
                                allocator, len, data);
}
void   spotv2__gyro__free_unpacked
                     (Spotv2__Gyro *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__gyro__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor spotv2__gyro__field_descriptors[30] =
{
  {
    "Accel_x",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, accel_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Accel_y",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, accel_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Accel_z",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, accel_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gyro_x",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, gyro_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gyro_y",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, gyro_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gyro_z",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, gyro_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mag_x",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, mag_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mag_y",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, mag_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mag_z",
    33,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, mag_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Grav_x",
    41,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, grav_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Grav_y",
    42,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, grav_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Grav_z",
    43,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, grav_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Linearaccel_x",
    51,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, linearaccel_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Linearaccel_y",
    52,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, linearaccel_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Linearaccel_z",
    53,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, linearaccel_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quat6_w",
    61,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, quat6_w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quat6_x",
    62,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, quat6_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quat6_y",
    63,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, quat6_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quat6_z",
    64,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, quat6_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quat9_w",
    71,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, quat9_w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quat9_x",
    72,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, quat9_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quat9_y",
    73,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, quat9_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quat9_z",
    74,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, quat9_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Euler6_roll",
    81,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, euler6_roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Euler6_pitch",
    82,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, euler6_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Euler6_yaw",
    83,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, euler6_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Euler9_roll",
    91,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, euler9_roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Euler9_pitch",
    92,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, euler9_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Euler9_yaw",
    93,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, euler9_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "steps",
    100,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Gyro, steps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__gyro__field_indices_by_name[] = {
  0,   /* field[0] = Accel_x */
  1,   /* field[1] = Accel_y */
  2,   /* field[2] = Accel_z */
  24,   /* field[24] = Euler6_pitch */
  23,   /* field[23] = Euler6_roll */
  25,   /* field[25] = Euler6_yaw */
  27,   /* field[27] = Euler9_pitch */
  26,   /* field[26] = Euler9_roll */
  28,   /* field[28] = Euler9_yaw */
  9,   /* field[9] = Grav_x */
  10,   /* field[10] = Grav_y */
  11,   /* field[11] = Grav_z */
  3,   /* field[3] = Gyro_x */
  4,   /* field[4] = Gyro_y */
  5,   /* field[5] = Gyro_z */
  12,   /* field[12] = Linearaccel_x */
  13,   /* field[13] = Linearaccel_y */
  14,   /* field[14] = Linearaccel_z */
  6,   /* field[6] = Mag_x */
  7,   /* field[7] = Mag_y */
  8,   /* field[8] = Mag_z */
  15,   /* field[15] = Quat6_w */
  16,   /* field[16] = Quat6_x */
  17,   /* field[17] = Quat6_y */
  18,   /* field[18] = Quat6_z */
  19,   /* field[19] = Quat9_w */
  20,   /* field[20] = Quat9_x */
  21,   /* field[21] = Quat9_y */
  22,   /* field[22] = Quat9_z */
  29,   /* field[29] = steps */
};
static const ProtobufCIntRange spotv2__gyro__number_ranges[10 + 1] =
{
  { 11, 0 },
  { 21, 3 },
  { 31, 6 },
  { 41, 9 },
  { 51, 12 },
  { 61, 15 },
  { 71, 19 },
  { 81, 23 },
  { 91, 26 },
  { 100, 29 },
  { 0, 30 }
};
const ProtobufCMessageDescriptor spotv2__gyro__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Gyro",
  "Gyro",
  "Spotv2__Gyro",
  "spotv2",
  sizeof(Spotv2__Gyro),
  30,
  spotv2__gyro__field_descriptors,
  spotv2__gyro__field_indices_by_name,
  10,  spotv2__gyro__number_ranges,
  (ProtobufCMessageInit) spotv2__gyro__init,
  NULL,NULL,NULL    /* reserved[123] */
};
