# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motion.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmotion.proto\x12\x06spotv2\"\x91\x01\n\x05Servo\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\r\n\x05speed\x18\x02 \x01(\x05\x12\x12\n\nresistance\x18\x03 \x01(\x05\x12#\n\x06status\x18\x04 \x01(\x0e\x32\x13.spotv2.ServoStatus\x12\x0c\n\x04temp\x18\x05 \x01(\x05\x12\x0f\n\x07voltage\x18\x06 \x01(\x05\x12\x0f\n\x07\x63urrent\x18\x07 \x01(\x05\"\xf4\x03\n\x06Motion\x12&\n\x0f\x46OOT_LEFT_FRONT\x18\x01 \x01(\x0b\x32\r.spotv2.Servo\x12\'\n\x10\x46OOT_RIGHT_FRONT\x18\x02 \x01(\x0b\x32\r.spotv2.Servo\x12%\n\x0e\x46OOT_LEFT_BACK\x18\x03 \x01(\x0b\x32\r.spotv2.Servo\x12&\n\x0f\x46OOT_RIGHT_BACK\x18\x04 \x01(\x0b\x32\r.spotv2.Servo\x12%\n\x0eLEG_LEFT_FRONT\x18\x05 \x01(\x0b\x32\r.spotv2.Servo\x12&\n\x0fLEG_RIGHT_FRONT\x18\x06 \x01(\x0b\x32\r.spotv2.Servo\x12$\n\rLEG_LEFT_BACK\x18\x07 \x01(\x0b\x32\r.spotv2.Servo\x12%\n\x0eLEG_RIGHT_BACK\x18\x08 \x01(\x0b\x32\r.spotv2.Servo\x12*\n\x13SHOULDER_LEFT_FRONT\x18\t \x01(\x0b\x32\r.spotv2.Servo\x12+\n\x14SHOULDER_RIGHT_FRONT\x18\n \x01(\x0b\x32\r.spotv2.Servo\x12)\n\x12SHOULDER_LEFT_BACK\x18\x0b \x01(\x0b\x32\r.spotv2.Servo\x12*\n\x13SHOULDER_RIGHT_BACK\x18\x0c \x01(\x0b\x32\r.spotv2.Servo\"1\n\x07\x43ommand\x12&\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x14.spotv2.CommandServo\"\x96\x01\n\x0c\x43ommandServo\x12\'\n\nmove_servo\x18\x01 \x01(\x0b\x32\x11.spotv2.MoveServoH\x00\x12\'\n\nstop_servo\x18\x02 \x01(\x0b\x32\x11.spotv2.StopServoH\x00\x12)\n\x0bstart_servo\x18\x03 \x01(\x0b\x32\x12.spotv2.StartServoH\x00\x42\t\n\x07\x63ommand\"E\n\tMoveServo\x12\x10\n\x08servo_id\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x03 \x01(\x05\"\x1d\n\tStopServo\x12\x10\n\x08servo_id\x18\x01 \x01(\x05\"\x1e\n\nStartServo\x12\x10\n\x08servo_id\x18\x01 \x01(\x05*>\n\x0bServoStatus\x12\x0b\n\x07STARTED\x10\x00\x12\x0b\n\x07STOPPED\x10\x01\x12\n\n\x06MOVING\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motion_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVOSTATUS._serialized_start=1013
  _SERVOSTATUS._serialized_end=1075
  _SERVO._serialized_start=25
  _SERVO._serialized_end=170
  _MOTION._serialized_start=173
  _MOTION._serialized_end=673
  _COMMAND._serialized_start=675
  _COMMAND._serialized_end=724
  _COMMANDSERVO._serialized_start=727
  _COMMANDSERVO._serialized_end=877
  _MOVESERVO._serialized_start=879
  _MOVESERVO._serialized_end=948
  _STOPSERVO._serialized_start=950
  _STOPSERVO._serialized_end=979
  _STARTSERVO._serialized_start=981
  _STARTSERVO._serialized_end=1011
# @@protoc_insertion_point(module_scope)
