/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: motion.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "motion.pb-c.h"
void   spotv2__servo__init
                     (Spotv2__Servo         *message)
{
  static const Spotv2__Servo init_value = SPOTV2__SERVO__INIT;
  *message = init_value;
}
size_t spotv2__servo__get_packed_size
                     (const Spotv2__Servo *message)
{
  assert(message->base.descriptor == &spotv2__servo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__servo__pack
                     (const Spotv2__Servo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__servo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__servo__pack_to_buffer
                     (const Spotv2__Servo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__servo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Servo *
       spotv2__servo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Servo *)
     protobuf_c_message_unpack (&spotv2__servo__descriptor,
                                allocator, len, data);
}
void   spotv2__servo__free_unpacked
                     (Spotv2__Servo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__servo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__motion__init
                     (Spotv2__Motion         *message)
{
  static const Spotv2__Motion init_value = SPOTV2__MOTION__INIT;
  *message = init_value;
}
size_t spotv2__motion__get_packed_size
                     (const Spotv2__Motion *message)
{
  assert(message->base.descriptor == &spotv2__motion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__motion__pack
                     (const Spotv2__Motion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__motion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__motion__pack_to_buffer
                     (const Spotv2__Motion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__motion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Motion *
       spotv2__motion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Motion *)
     protobuf_c_message_unpack (&spotv2__motion__descriptor,
                                allocator, len, data);
}
void   spotv2__motion__free_unpacked
                     (Spotv2__Motion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__motion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__command__init
                     (Spotv2__Command         *message)
{
  static const Spotv2__Command init_value = SPOTV2__COMMAND__INIT;
  *message = init_value;
}
size_t spotv2__command__get_packed_size
                     (const Spotv2__Command *message)
{
  assert(message->base.descriptor == &spotv2__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__command__pack
                     (const Spotv2__Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__command__pack_to_buffer
                     (const Spotv2__Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Command *
       spotv2__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Command *)
     protobuf_c_message_unpack (&spotv2__command__descriptor,
                                allocator, len, data);
}
void   spotv2__command__free_unpacked
                     (Spotv2__Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__command_servo__init
                     (Spotv2__CommandServo         *message)
{
  static const Spotv2__CommandServo init_value = SPOTV2__COMMAND_SERVO__INIT;
  *message = init_value;
}
size_t spotv2__command_servo__get_packed_size
                     (const Spotv2__CommandServo *message)
{
  assert(message->base.descriptor == &spotv2__command_servo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__command_servo__pack
                     (const Spotv2__CommandServo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__command_servo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__command_servo__pack_to_buffer
                     (const Spotv2__CommandServo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__command_servo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__CommandServo *
       spotv2__command_servo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__CommandServo *)
     protobuf_c_message_unpack (&spotv2__command_servo__descriptor,
                                allocator, len, data);
}
void   spotv2__command_servo__free_unpacked
                     (Spotv2__CommandServo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__command_servo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__move_servo__init
                     (Spotv2__MoveServo         *message)
{
  static const Spotv2__MoveServo init_value = SPOTV2__MOVE_SERVO__INIT;
  *message = init_value;
}
size_t spotv2__move_servo__get_packed_size
                     (const Spotv2__MoveServo *message)
{
  assert(message->base.descriptor == &spotv2__move_servo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__move_servo__pack
                     (const Spotv2__MoveServo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__move_servo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__move_servo__pack_to_buffer
                     (const Spotv2__MoveServo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__move_servo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__MoveServo *
       spotv2__move_servo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__MoveServo *)
     protobuf_c_message_unpack (&spotv2__move_servo__descriptor,
                                allocator, len, data);
}
void   spotv2__move_servo__free_unpacked
                     (Spotv2__MoveServo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__move_servo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__stop_servo__init
                     (Spotv2__StopServo         *message)
{
  static const Spotv2__StopServo init_value = SPOTV2__STOP_SERVO__INIT;
  *message = init_value;
}
size_t spotv2__stop_servo__get_packed_size
                     (const Spotv2__StopServo *message)
{
  assert(message->base.descriptor == &spotv2__stop_servo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__stop_servo__pack
                     (const Spotv2__StopServo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__stop_servo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__stop_servo__pack_to_buffer
                     (const Spotv2__StopServo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__stop_servo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__StopServo *
       spotv2__stop_servo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__StopServo *)
     protobuf_c_message_unpack (&spotv2__stop_servo__descriptor,
                                allocator, len, data);
}
void   spotv2__stop_servo__free_unpacked
                     (Spotv2__StopServo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__stop_servo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__start_servo__init
                     (Spotv2__StartServo         *message)
{
  static const Spotv2__StartServo init_value = SPOTV2__START_SERVO__INIT;
  *message = init_value;
}
size_t spotv2__start_servo__get_packed_size
                     (const Spotv2__StartServo *message)
{
  assert(message->base.descriptor == &spotv2__start_servo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__start_servo__pack
                     (const Spotv2__StartServo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__start_servo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__start_servo__pack_to_buffer
                     (const Spotv2__StartServo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__start_servo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__StartServo *
       spotv2__start_servo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__StartServo *)
     protobuf_c_message_unpack (&spotv2__start_servo__descriptor,
                                allocator, len, data);
}
void   spotv2__start_servo__free_unpacked
                     (Spotv2__StartServo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__start_servo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor spotv2__servo__field_descriptors[7] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Servo, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Servo, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resistance",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Servo, resistance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Servo, status),
    &spotv2__servo_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Servo, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Servo, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Servo, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__servo__field_indices_by_name[] = {
  6,   /* field[6] = current */
  0,   /* field[0] = position */
  2,   /* field[2] = resistance */
  1,   /* field[1] = speed */
  3,   /* field[3] = status */
  4,   /* field[4] = temp */
  5,   /* field[5] = voltage */
};
static const ProtobufCIntRange spotv2__servo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor spotv2__servo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Servo",
  "Servo",
  "Spotv2__Servo",
  "spotv2",
  sizeof(Spotv2__Servo),
  7,
  spotv2__servo__field_descriptors,
  spotv2__servo__field_indices_by_name,
  1,  spotv2__servo__number_ranges,
  (ProtobufCMessageInit) spotv2__servo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__motion__field_descriptors[12] =
{
  {
    "FOOT_LEFT_FRONT",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, foot_left_front),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FOOT_RIGHT_FRONT",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, foot_right_front),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FOOT_LEFT_BACK",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, foot_left_back),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FOOT_RIGHT_BACK",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, foot_right_back),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LEG_LEFT_FRONT",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, leg_left_front),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LEG_RIGHT_FRONT",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, leg_right_front),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LEG_LEFT_BACK",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, leg_left_back),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LEG_RIGHT_BACK",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, leg_right_back),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SHOULDER_LEFT_FRONT",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, shoulder_left_front),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SHOULDER_RIGHT_FRONT",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, shoulder_right_front),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SHOULDER_LEFT_BACK",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, shoulder_left_back),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SHOULDER_RIGHT_BACK",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Motion, shoulder_right_back),
    &spotv2__servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__motion__field_indices_by_name[] = {
  2,   /* field[2] = FOOT_LEFT_BACK */
  0,   /* field[0] = FOOT_LEFT_FRONT */
  3,   /* field[3] = FOOT_RIGHT_BACK */
  1,   /* field[1] = FOOT_RIGHT_FRONT */
  6,   /* field[6] = LEG_LEFT_BACK */
  4,   /* field[4] = LEG_LEFT_FRONT */
  7,   /* field[7] = LEG_RIGHT_BACK */
  5,   /* field[5] = LEG_RIGHT_FRONT */
  10,   /* field[10] = SHOULDER_LEFT_BACK */
  8,   /* field[8] = SHOULDER_LEFT_FRONT */
  11,   /* field[11] = SHOULDER_RIGHT_BACK */
  9,   /* field[9] = SHOULDER_RIGHT_FRONT */
};
static const ProtobufCIntRange spotv2__motion__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor spotv2__motion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Motion",
  "Motion",
  "Spotv2__Motion",
  "spotv2",
  sizeof(Spotv2__Motion),
  12,
  spotv2__motion__field_descriptors,
  spotv2__motion__field_indices_by_name,
  1,  spotv2__motion__number_ranges,
  (ProtobufCMessageInit) spotv2__motion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__command__field_descriptors[1] =
{
  {
    "commands",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Spotv2__Command, n_commands),
    offsetof(Spotv2__Command, commands),
    &spotv2__command_servo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__command__field_indices_by_name[] = {
  0,   /* field[0] = commands */
};
static const ProtobufCIntRange spotv2__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor spotv2__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Command",
  "Command",
  "Spotv2__Command",
  "spotv2",
  sizeof(Spotv2__Command),
  1,
  spotv2__command__field_descriptors,
  spotv2__command__field_indices_by_name,
  1,  spotv2__command__number_ranges,
  (ProtobufCMessageInit) spotv2__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__command_servo__field_descriptors[3] =
{
  {
    "move_servo",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Spotv2__CommandServo, command_case),
    offsetof(Spotv2__CommandServo, move_servo),
    &spotv2__move_servo__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_servo",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Spotv2__CommandServo, command_case),
    offsetof(Spotv2__CommandServo, stop_servo),
    &spotv2__stop_servo__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_servo",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Spotv2__CommandServo, command_case),
    offsetof(Spotv2__CommandServo, start_servo),
    &spotv2__start_servo__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__command_servo__field_indices_by_name[] = {
  0,   /* field[0] = move_servo */
  2,   /* field[2] = start_servo */
  1,   /* field[1] = stop_servo */
};
static const ProtobufCIntRange spotv2__command_servo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__command_servo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.CommandServo",
  "CommandServo",
  "Spotv2__CommandServo",
  "spotv2",
  sizeof(Spotv2__CommandServo),
  3,
  spotv2__command_servo__field_descriptors,
  spotv2__command_servo__field_indices_by_name,
  1,  spotv2__command_servo__number_ranges,
  (ProtobufCMessageInit) spotv2__command_servo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__move_servo__field_descriptors[3] =
{
  {
    "servo_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__MoveServo, servo_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__MoveServo, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acceleration",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__MoveServo, acceleration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__move_servo__field_indices_by_name[] = {
  2,   /* field[2] = acceleration */
  1,   /* field[1] = position */
  0,   /* field[0] = servo_id */
};
static const ProtobufCIntRange spotv2__move_servo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__move_servo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.MoveServo",
  "MoveServo",
  "Spotv2__MoveServo",
  "spotv2",
  sizeof(Spotv2__MoveServo),
  3,
  spotv2__move_servo__field_descriptors,
  spotv2__move_servo__field_indices_by_name,
  1,  spotv2__move_servo__number_ranges,
  (ProtobufCMessageInit) spotv2__move_servo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__stop_servo__field_descriptors[1] =
{
  {
    "servo_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__StopServo, servo_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__stop_servo__field_indices_by_name[] = {
  0,   /* field[0] = servo_id */
};
static const ProtobufCIntRange spotv2__stop_servo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor spotv2__stop_servo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.StopServo",
  "StopServo",
  "Spotv2__StopServo",
  "spotv2",
  sizeof(Spotv2__StopServo),
  1,
  spotv2__stop_servo__field_descriptors,
  spotv2__stop_servo__field_indices_by_name,
  1,  spotv2__stop_servo__number_ranges,
  (ProtobufCMessageInit) spotv2__stop_servo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__start_servo__field_descriptors[1] =
{
  {
    "servo_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__StartServo, servo_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__start_servo__field_indices_by_name[] = {
  0,   /* field[0] = servo_id */
};
static const ProtobufCIntRange spotv2__start_servo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor spotv2__start_servo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.StartServo",
  "StartServo",
  "Spotv2__StartServo",
  "spotv2",
  sizeof(Spotv2__StartServo),
  1,
  spotv2__start_servo__field_descriptors,
  spotv2__start_servo__field_indices_by_name,
  1,  spotv2__start_servo__number_ranges,
  (ProtobufCMessageInit) spotv2__start_servo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue spotv2__servo_status__enum_values_by_number[4] =
{
  { "STARTED", "SPOTV2__SERVO_STATUS__STARTED", 0 },
  { "STOPPED", "SPOTV2__SERVO_STATUS__STOPPED", 1 },
  { "MOVING", "SPOTV2__SERVO_STATUS__MOVING", 2 },
  { "ERROR", "SPOTV2__SERVO_STATUS__ERROR", 3 },
};
static const ProtobufCIntRange spotv2__servo_status__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex spotv2__servo_status__enum_values_by_name[4] =
{
  { "ERROR", 3 },
  { "MOVING", 2 },
  { "STARTED", 0 },
  { "STOPPED", 1 },
};
const ProtobufCEnumDescriptor spotv2__servo_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "spotv2.ServoStatus",
  "ServoStatus",
  "Spotv2__ServoStatus",
  "spotv2",
  4,
  spotv2__servo_status__enum_values_by_number,
  4,
  spotv2__servo_status__enum_values_by_name,
  1,
  spotv2__servo_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
