/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vision.proto */

#ifndef PROTOBUF_C_vision_2eproto__INCLUDED
#define PROTOBUF_C_vision_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"

typedef struct Spotv2__Position Spotv2__Position;
typedef struct Spotv2__Box Spotv2__Box;
typedef struct Spotv2__Object Spotv2__Object;
typedef struct Spotv2__Objects Spotv2__Objects;


/* --- enums --- */


/* --- messages --- */

struct  Spotv2__Position
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
};
#define SPOTV2__POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__position__descriptor) \
, 0, 0 }


struct  Spotv2__Box
{
  ProtobufCMessage base;
  Spotv2__Position *first;
  Spotv2__Position *last;
};
#define SPOTV2__BOX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__box__descriptor) \
, NULL, NULL }


struct  Spotv2__Object
{
  ProtobufCMessage base;
  Spotv2__Box *box;
  char *type;
  float proba;
};
#define SPOTV2__OBJECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__object__descriptor) \
, NULL, (char *)protobuf_c_empty_string, 0 }


struct  Spotv2__Objects
{
  ProtobufCMessage base;
  Google__Protobuf__Timestamp *timestamp;
  size_t n_objets;
  Spotv2__Object **objets;
};
#define SPOTV2__OBJECTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&spotv2__objects__descriptor) \
, NULL, 0,NULL }


/* Spotv2__Position methods */
void   spotv2__position__init
                     (Spotv2__Position         *message);
size_t spotv2__position__get_packed_size
                     (const Spotv2__Position   *message);
size_t spotv2__position__pack
                     (const Spotv2__Position   *message,
                      uint8_t             *out);
size_t spotv2__position__pack_to_buffer
                     (const Spotv2__Position   *message,
                      ProtobufCBuffer     *buffer);
Spotv2__Position *
       spotv2__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   spotv2__position__free_unpacked
                     (Spotv2__Position *message,
                      ProtobufCAllocator *allocator);
/* Spotv2__Box methods */
void   spotv2__box__init
                     (Spotv2__Box         *message);
size_t spotv2__box__get_packed_size
                     (const Spotv2__Box   *message);
size_t spotv2__box__pack
                     (const Spotv2__Box   *message,
                      uint8_t             *out);
size_t spotv2__box__pack_to_buffer
                     (const Spotv2__Box   *message,
                      ProtobufCBuffer     *buffer);
Spotv2__Box *
       spotv2__box__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   spotv2__box__free_unpacked
                     (Spotv2__Box *message,
                      ProtobufCAllocator *allocator);
/* Spotv2__Object methods */
void   spotv2__object__init
                     (Spotv2__Object         *message);
size_t spotv2__object__get_packed_size
                     (const Spotv2__Object   *message);
size_t spotv2__object__pack
                     (const Spotv2__Object   *message,
                      uint8_t             *out);
size_t spotv2__object__pack_to_buffer
                     (const Spotv2__Object   *message,
                      ProtobufCBuffer     *buffer);
Spotv2__Object *
       spotv2__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   spotv2__object__free_unpacked
                     (Spotv2__Object *message,
                      ProtobufCAllocator *allocator);
/* Spotv2__Objects methods */
void   spotv2__objects__init
                     (Spotv2__Objects         *message);
size_t spotv2__objects__get_packed_size
                     (const Spotv2__Objects   *message);
size_t spotv2__objects__pack
                     (const Spotv2__Objects   *message,
                      uint8_t             *out);
size_t spotv2__objects__pack_to_buffer
                     (const Spotv2__Objects   *message,
                      ProtobufCBuffer     *buffer);
Spotv2__Objects *
       spotv2__objects__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   spotv2__objects__free_unpacked
                     (Spotv2__Objects *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Spotv2__Position_Closure)
                 (const Spotv2__Position *message,
                  void *closure_data);
typedef void (*Spotv2__Box_Closure)
                 (const Spotv2__Box *message,
                  void *closure_data);
typedef void (*Spotv2__Object_Closure)
                 (const Spotv2__Object *message,
                  void *closure_data);
typedef void (*Spotv2__Objects_Closure)
                 (const Spotv2__Objects *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor spotv2__position__descriptor;
extern const ProtobufCMessageDescriptor spotv2__box__descriptor;
extern const ProtobufCMessageDescriptor spotv2__object__descriptor;
extern const ProtobufCMessageDescriptor spotv2__objects__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_vision_2eproto__INCLUDED */
