# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06spotv2\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"F\n\x03\x42ox\x12\x1f\n\x05\x66irst\x18\x01 \x01(\x0b\x32\x10.spotv2.Position\x12\x1e\n\x04last\x18\x02 \x01(\x0b\x32\x10.spotv2.Position\"?\n\x06Object\x12\x18\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x0b.spotv2.Box\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05proba\x18\x03 \x01(\x02\"<\n\x07Objects\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x1e\n\x06objets\x18\x02 \x03(\x0b\x32\x0e.spotv2.Objectb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSITION._serialized_start=24
  _POSITION._serialized_end=56
  _BOX._serialized_start=58
  _BOX._serialized_end=128
  _OBJECT._serialized_start=130
  _OBJECT._serialized_end=193
  _OBJECTS._serialized_start=195
  _OBJECTS._serialized_end=255
# @@protoc_insertion_point(module_scope)
