/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vision.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "vision.pb-c.h"
void   spotv2__position__init
                     (Spotv2__Position         *message)
{
  static const Spotv2__Position init_value = SPOTV2__POSITION__INIT;
  *message = init_value;
}
size_t spotv2__position__get_packed_size
                     (const Spotv2__Position *message)
{
  assert(message->base.descriptor == &spotv2__position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__position__pack
                     (const Spotv2__Position *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__position__pack_to_buffer
                     (const Spotv2__Position *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Position *
       spotv2__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Position *)
     protobuf_c_message_unpack (&spotv2__position__descriptor,
                                allocator, len, data);
}
void   spotv2__position__free_unpacked
                     (Spotv2__Position *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__box__init
                     (Spotv2__Box         *message)
{
  static const Spotv2__Box init_value = SPOTV2__BOX__INIT;
  *message = init_value;
}
size_t spotv2__box__get_packed_size
                     (const Spotv2__Box *message)
{
  assert(message->base.descriptor == &spotv2__box__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__box__pack
                     (const Spotv2__Box *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__box__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__box__pack_to_buffer
                     (const Spotv2__Box *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__box__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Box *
       spotv2__box__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Box *)
     protobuf_c_message_unpack (&spotv2__box__descriptor,
                                allocator, len, data);
}
void   spotv2__box__free_unpacked
                     (Spotv2__Box *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__box__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__object__init
                     (Spotv2__Object         *message)
{
  static const Spotv2__Object init_value = SPOTV2__OBJECT__INIT;
  *message = init_value;
}
size_t spotv2__object__get_packed_size
                     (const Spotv2__Object *message)
{
  assert(message->base.descriptor == &spotv2__object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__object__pack
                     (const Spotv2__Object *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__object__pack_to_buffer
                     (const Spotv2__Object *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Object *
       spotv2__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Object *)
     protobuf_c_message_unpack (&spotv2__object__descriptor,
                                allocator, len, data);
}
void   spotv2__object__free_unpacked
                     (Spotv2__Object *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   spotv2__objects__init
                     (Spotv2__Objects         *message)
{
  static const Spotv2__Objects init_value = SPOTV2__OBJECTS__INIT;
  *message = init_value;
}
size_t spotv2__objects__get_packed_size
                     (const Spotv2__Objects *message)
{
  assert(message->base.descriptor == &spotv2__objects__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t spotv2__objects__pack
                     (const Spotv2__Objects *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &spotv2__objects__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t spotv2__objects__pack_to_buffer
                     (const Spotv2__Objects *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &spotv2__objects__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Spotv2__Objects *
       spotv2__objects__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Spotv2__Objects *)
     protobuf_c_message_unpack (&spotv2__objects__descriptor,
                                allocator, len, data);
}
void   spotv2__objects__free_unpacked
                     (Spotv2__Objects *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &spotv2__objects__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor spotv2__position__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Position, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Position, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__position__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange spotv2__position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor spotv2__position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Position",
  "Position",
  "Spotv2__Position",
  "spotv2",
  sizeof(Spotv2__Position),
  2,
  spotv2__position__field_descriptors,
  spotv2__position__field_indices_by_name,
  1,  spotv2__position__number_ranges,
  (ProtobufCMessageInit) spotv2__position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__box__field_descriptors[2] =
{
  {
    "first",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Box, first),
    &spotv2__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Box, last),
    &spotv2__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__box__field_indices_by_name[] = {
  0,   /* field[0] = first */
  1,   /* field[1] = last */
};
static const ProtobufCIntRange spotv2__box__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor spotv2__box__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Box",
  "Box",
  "Spotv2__Box",
  "spotv2",
  sizeof(Spotv2__Box),
  2,
  spotv2__box__field_descriptors,
  spotv2__box__field_indices_by_name,
  1,  spotv2__box__number_ranges,
  (ProtobufCMessageInit) spotv2__box__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__object__field_descriptors[3] =
{
  {
    "box",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Object, box),
    &spotv2__box__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Object, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proba",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Object, proba),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__object__field_indices_by_name[] = {
  0,   /* field[0] = box */
  2,   /* field[2] = proba */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange spotv2__object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor spotv2__object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Object",
  "Object",
  "Spotv2__Object",
  "spotv2",
  sizeof(Spotv2__Object),
  3,
  spotv2__object__field_descriptors,
  spotv2__object__field_indices_by_name,
  1,  spotv2__object__number_ranges,
  (ProtobufCMessageInit) spotv2__object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor spotv2__objects__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Spotv2__Objects, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "objets",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Spotv2__Objects, n_objets),
    offsetof(Spotv2__Objects, objets),
    &spotv2__object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned spotv2__objects__field_indices_by_name[] = {
  1,   /* field[1] = objets */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange spotv2__objects__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor spotv2__objects__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "spotv2.Objects",
  "Objects",
  "Spotv2__Objects",
  "spotv2",
  sizeof(Spotv2__Objects),
  2,
  spotv2__objects__field_descriptors,
  spotv2__objects__field_indices_by_name,
  1,  spotv2__objects__number_ranges,
  (ProtobufCMessageInit) spotv2__objects__init,
  NULL,NULL,NULL    /* reserved[123] */
};
