# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06spotv2\x1a\x1fgoogle/protobuf/timestamp.proto\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"F\n\x03\x42ox\x12\x1f\n\x05\x66irst\x18\x01 \x01(\x0b\x32\x10.spotv2.Position\x12\x1e\n\x04last\x18\x02 \x01(\x0b\x32\x10.spotv2.Position\"?\n\x06Object\x12\x18\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x0b.spotv2.Box\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05proba\x18\x03 \x01(\x02\"X\n\x07Objects\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x06objets\x18\x02 \x03(\x0b\x32\x0e.spotv2.Objectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSITION']._serialized_start=57
  _globals['_POSITION']._serialized_end=89
  _globals['_BOX']._serialized_start=91
  _globals['_BOX']._serialized_end=161
  _globals['_OBJECT']._serialized_start=163
  _globals['_OBJECT']._serialized_end=226
  _globals['_OBJECTS']._serialized_start=228
  _globals['_OBJECTS']._serialized_end=316
# @@protoc_insertion_point(module_scope)
